// 定义类型常量
// 全局常量定义
const ACCOUNT = "ACCOUTN" // 钱包地址
const SHOW_ACCOUNT = "SHOW_ACCOUNT"
const CHAINID = "CHAINID" // 当前链 ID
const NETWORK = "NETWORK" // 当前网络
const DIALOG_TYPE = "DIALOG_TYPE" // 一级弹窗类型
const WALLET_DIALOG_TYPE = "WALLET_DIALOG_TYPE" // 钱包弹窗
const INPUT_VALUE = "INPUT_VALUE" // 输入框绑定值
const COIN_PRICE = "COIN_PRICE" // 币种价格
const IS_MOBILE = "IS_MOBILE" // 是否是移动端
const IS_CONNECT = "IS_CONNECT" // 网络是否已连接
const NETWORK_NAME = "NETWORK_NAME" // 网络名称

// 市场页面常量定义
const MARKET_LISTS = "MARKET_LISTS" // 市场列表
const MARKET_ITEM_INDEX = "MARKET_ITEM_INDEX" // 点击的列表 item 角标值

// 资产管理页面常量定义
const ASSETS_LISTS = "ASSETS_LISTS" // 资产管理列表
const ASSETS_ITEM_INDEX = "ASSETS_ITEM_INDEX" // 点击的资产管理列表 item 角标值

// 杠杆交易页面常量
const SWAP_LEVERAGE_SLIDE_VALUE = "SWAP_LEVERAGE_SLIDE_VALUE"
const SWAP_LISTS = "SWAP_LISTS"
const SWAP_INDEX = "SWAP_INDEX"
const SWAP_TOKEN_NAME = "SWAP_TOKEN_NAME"
const SWAP_TOKEN_ADDRESS = "SWAP_TOKEN_ADDRESS"
const COIN_BALANCE = "COIN_BALANCE"
const SWAP_P_TOKEN_ADDRESS = "SWAP_P_TOKEN_ADDRESS"
const SWAP_DECIMAL = "SWAP_DECIMAL"

export default {
  ACCOUNT,
  CHAINID,
  NETWORK,
  DIALOG_TYPE,
  WALLET_DIALOG_TYPE,
  INPUT_VALUE,
  COIN_PRICE,
  IS_MOBILE,
  MARKET_LISTS,
  MARKET_ITEM_INDEX,
  ASSETS_LISTS,
  ASSETS_ITEM_INDEX,
  SWAP_LEVERAGE_SLIDE_VALUE,
  SHOW_ACCOUNT,
  IS_CONNECT,
  NETWORK_NAME,
  SWAP_LISTS,
  SWAP_INDEX,
  SWAP_TOKEN_NAME,
  SWAP_TOKEN_ADDRESS,
  COIN_BALANCE,
  SWAP_P_TOKEN_ADDRESS,
  SWAP_DECIMAL
}